package com.mlbstats.api.dto;

import com.mlbstats.domain.stats.PlayerBattingStats;

import java.math.BigDecimal;

public record BattingStatsDto(
        Long id,
        PlayerDto player,
        TeamDto team,
        Integer season,
        String gameType,
        Integer gamesPlayed,
        Integer atBats,
        Integer runs,
        Integer hits,
        Integer doubles,
        Integer triples,
        Integer homeRuns,
        Integer rbi,
        Integer stolenBases,
        Integer caughtStealing,
        Integer walks,
        Integer strikeouts,
        BigDecimal battingAvg,
        BigDecimal obp,
        BigDecimal slg,
        BigDecimal ops,
        BigDecimal babip,
        BigDecimal iso,
        Integer plateAppearances,
        Integer totalBases,
        Integer extraBaseHits,
        // Advanced Sabermetric Stats
        BigDecimal war,
        BigDecimal woba,
        Integer wrcPlus,
        BigDecimal hardHitPct,
        BigDecimal barrelPct,
        BigDecimal avgExitVelocity,
        BigDecimal avgLaunchAngle,
        BigDecimal sprintSpeed,
        BigDecimal xba,
        BigDecimal xslg,
        BigDecimal xwoba,
        BigDecimal kPct,
        BigDecimal bbPct,
        // gWAR (Grove WAR) fields
        BigDecimal gwar,
        BigDecimal gwarBatting,
        BigDecimal gwarBaserunning,
        BigDecimal gwarFielding,
        BigDecimal gwarPositional,
        BigDecimal gwarReplacement,
        Integer oaa
) {
    public static BattingStatsDto fromEntity(PlayerBattingStats stats) {
        return new BattingStatsDto(
                stats.getId(),
                stats.getPlayer() != null ? PlayerDto.fromEntity(stats.getPlayer()) : null,
                stats.getTeam() != null ? TeamDto.fromEntity(stats.getTeam()) : null,
                stats.getSeason(),
                stats.getGameType(),
                stats.getGamesPlayed(),
                stats.getAtBats(),
                stats.getRuns(),
                stats.getHits(),
                stats.getDoubles(),
                stats.getTriples(),
                stats.getHomeRuns(),
                stats.getRbi(),
                stats.getStolenBases(),
                stats.getCaughtStealing(),
                stats.getWalks(),
                stats.getStrikeouts(),
                stats.getBattingAvg(),
                stats.getObp(),
                stats.getSlg(),
                stats.getOps(),
                stats.getBabip(),
                stats.getIso(),
                stats.getPlateAppearances(),
                stats.getTotalBases(),
                stats.getExtraBaseHits(),
                stats.getWar(),
                stats.getWoba(),
                stats.getWrcPlus(),
                stats.getHardHitPct(),
                stats.getBarrelPct(),
                stats.getAvgExitVelocity(),
                stats.getAvgLaunchAngle(),
                stats.getSprintSpeed(),
                stats.getXba(),
                stats.getXslg(),
                stats.getXwoba(),
                stats.getKPct(),
                stats.getBbPct(),
                stats.getGwar(),
                stats.getGwarBatting(),
                stats.getGwarBaserunning(),
                stats.getGwarFielding(),
                stats.getGwarPositional(),
                stats.getGwarReplacement(),
                stats.getOaa()
        );
    }
}
