package com.mlbstats.api.dto;

import com.mlbstats.domain.stats.PlayerPitchingStats;

import java.math.BigDecimal;

public record PitchingStatsDto(
        Long id,
        PlayerDto player,
        TeamDto team,
        Integer season,
        String gameType,
        Integer gamesPlayed,
        Integer gamesStarted,
        Integer wins,
        Integer losses,
        Integer saves,
        Integer holds,
        BigDecimal inningsPitched,
        Integer hitsAllowed,
        Integer runsAllowed,
        Integer earnedRuns,
        Integer homeRunsAllowed,
        Integer walks,
        Integer strikeouts,
        BigDecimal era,
        BigDecimal whip,
        BigDecimal kPer9,
        BigDecimal bbPer9,
        BigDecimal hPer9,
        Integer completeGames,
        Integer shutouts,
        // Advanced Sabermetric Stats
        BigDecimal war,
        BigDecimal fip,
        BigDecimal xfip,
        BigDecimal siera,
        BigDecimal kPct,
        BigDecimal bbPct,
        BigDecimal gbPct,
        BigDecimal fbPct,
        BigDecimal hardHitPctAgainst,
        BigDecimal avgExitVelocityAgainst,
        BigDecimal xera,
        Integer avgSpinRate,
        BigDecimal whiffPct,
        BigDecimal chasePct,
        // gWAR (Grove WAR) fields
        BigDecimal gwar,
        BigDecimal gwarPitching,
        BigDecimal gwarReplacement
) {
    public static PitchingStatsDto fromEntity(PlayerPitchingStats stats) {
        return new PitchingStatsDto(
                stats.getId(),
                stats.getPlayer() != null ? PlayerDto.fromEntity(stats.getPlayer()) : null,
                stats.getTeam() != null ? TeamDto.fromEntity(stats.getTeam()) : null,
                stats.getSeason(),
                stats.getGameType(),
                stats.getGamesPlayed(),
                stats.getGamesStarted(),
                stats.getWins(),
                stats.getLosses(),
                stats.getSaves(),
                stats.getHolds(),
                stats.getInningsPitched(),
                stats.getHitsAllowed(),
                stats.getRunsAllowed(),
                stats.getEarnedRuns(),
                stats.getHomeRunsAllowed(),
                stats.getWalks(),
                stats.getStrikeouts(),
                stats.getEra(),
                stats.getWhip(),
                stats.getKPer9(),
                stats.getBbPer9(),
                stats.getHPer9(),
                stats.getCompleteGames(),
                stats.getShutouts(),
                stats.getWar(),
                stats.getFip(),
                stats.getXfip(),
                stats.getSiera(),
                stats.getKPct(),
                stats.getBbPct(),
                stats.getGbPct(),
                stats.getFbPct(),
                stats.getHardHitPctAgainst(),
                stats.getAvgExitVelocityAgainst(),
                stats.getXera(),
                stats.getAvgSpinRate(),
                stats.getWhiffPct(),
                stats.getChasePct(),
                stats.getGwar(),
                stats.getGwarPitching(),
                stats.getGwarReplacement()
        );
    }
}
